name = "sculptor"
license = "MIT"
description = ""
min_version = "0.1"

[author]
  name = "Daniel Gómez"
  homepage = "https://www.sadmedia.com"

[original]
  name = "sculptor"
  author = "Daniel Gómez"
